# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quote_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='user_quote',
            field=models.ManyToManyField(to='login.Quote'),
        ),
    ]
