# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170127_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Users')),
                ('quote', models.ManyToManyField(to='login.Quote')),
            ],
        ),
    ]
