# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170127_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Liked',
        ),
        migrations.RenameField(
            model_name='liked',
            old_name='owned_by',
            new_name='liked_by',
        ),
    ]
