# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20170127_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='quoter',
            field=models.ManyToManyField(to='login.Users'),
        ),
    ]
