# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20170127_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quoter',
        ),
    ]
