# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_quote_quoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quoter',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteowner', to='login.Users'),
        ),
    ]
