# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20170127_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='liked',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quoter',
        ),
        migrations.AddField(
            model_name='quote',
            name='liked',
            field=models.ManyToManyField(to='login.Users'),
        ),
    ]
