# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20170127_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ManyToManyField(to='login.Users')),
                ('quote_id', models.ManyToManyField(to='login.Quote')),
            ],
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
