# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20170127_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='liked',
            new_name='made_by',
        ),
    ]
