# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20170127_2336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='made_by',
        ),
        migrations.AddField(
            model_name='quote',
            name='made_by',
            field=models.ForeignKey(default=0, max_length=140, on_delete=django.db.models.deletion.CASCADE, to='login.Users'),
        ),
    ]
