# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 01:45
from __future__ import unicode_literals

import apps.login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_remove_quote_made_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='made_by',
            field=models.CharField(default=0, max_length=140, verbose_name=apps.login.models.Users),
        ),
    ]
