# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_quote_made_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='made_by',
        ),
        migrations.AddField(
            model_name='users',
            name='liked',
            field=models.ManyToManyField(to='login.Quote'),
        ),
    ]
