# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20170128_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotejoin',
            name='quote_id',
        ),
    ]
