# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_remove_quotejoin_quote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotejoin',
            name='liked_by',
        ),
    ]
