# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_auto_20170128_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='liked',
        ),
        migrations.AddField(
            model_name='quote',
            name='liked',
            field=models.ManyToManyField(related_name='liked_quote', to='login.Quote'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_owner', to='login.Users'),
        ),
    ]
