# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_auto_20170128_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='liked',
            field=models.ManyToManyField(related_name='likedquote', to='login.Quote'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteowner', to='login.Users'),
        ),
    ]
