# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_auto_20170128_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='liked',
        ),
        migrations.AddField(
            model_name='users',
            name='liked',
            field=models.ManyToManyField(related_name='likedquote', to='login.Quote'),
        ),
    ]
