# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_auto_20170128_2348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liked',
            new_name='Favorite',
        ),
    ]
